### ISSUE TITLE
making new block makes a private void

### ISSUE THREAD

**Issue by theking465** [VubbiScript/VubbiScript#14]
If you make your own block it creates a private void, instead it should create public void so you can use that function elsewhere.

**Comment by jeroenpx** [comment]
Hello theking465,

I am not sure this is needed.

VubbiScript already has "messages" blocks. Using the "messages" blocks allows you to call blocks inside another script. That is probably the better way of calling blocks in other scripts since you can really use a block to call it from the other script. You don't have to write C# to call the other script.

I could however change it so the script blocks also create public methods for the advanced users. But before I do that, did you know of/try the "messages" blocks?

Kind regards,
Jeroen

**Comment by theking465** [comment]
No I haven't.
The problem I had was that I created some kind of playermovement. Each
direction was another function. I then tried to attach those functions to a
button that I use a a joystick. this wasn't possible as buttons can only
use public voids.

Op zo 17 mrt. 2019 10:31 schreef Jeroen Penninck <notifications@github.com>:

**Comment by jeroenpx** [comment]
Ok, so you are using some external script to attach the functions to specific events. 
Hmm... Message blocks would be a simple workaround, but maybe I should indeed consider making code blocks public as well.

**Comment by theking465** [comment]
I'd suggest to make them public, it doesn't has any negative consequences
as far as I'm concerned

Op zo 17 mrt. 2019 16:30 schreef Jeroen Penninck <notifications@github.com>:
