### ISSUE TITLE
can something like this be made for runtime use?

### ISSUE THREAD

**Issue by RYG81** [VubbiScript/VubbiScript#15]
Hi,
It looks really good but is it possible to have this in game, at run time?
To teach kids programming and understand logic?

**Comment by jeroenpx** [comment]
Hello RYG81,
It could be interesting to have something like this inside a game. I think it can be done but it would need some changes related to "saving of the code".

The UI is built on Blockly which is a Javascript library maintained by Google. So the UI you see is written in HTML and JavaScript. This means that if you can display a browser view in the game you can display and edit the blocks. (so that part is probably quite easy :) )

When you save however, I currently convert the xml structure describing the blocks and their positions to a C# script and write this to a file. You can then use this C# file as a component and add to Unity GameObjects.
If you want to be able to execute the code while the game is running you probably don't want to do this conversion but instead just run the code directly (Instead of writing a string saying "Debug.Log(" to some file, just execute "Debug.Log("...) That way you can probably also easily add debugging features (step, play, pause, restart?).

But yes, it is definitely possible. What kind of game did you have in mind?

Also, I am not sure if you know this site, but code.org does something with games that teach kids to program: https://code.org/ (it is also built on Blockly)

Kind regards,
Jeroen
